title: Alte Lesart
lang: de
description: Ein deutsches Quellen-, Lese- und Wissensnetz für alte hebräische Texte.
markdown: kramdown
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
  - NOTICE.md
exclude:
  - _topic_manifest.json
  - _templates
  - Gemfile
  - Gemfile.lock
  - scripts
  - vendor
permalink: pretty
